export enum ErrorCodes {
  INVALID_REQUEST = 'invalid_request',
  LEAD_NOT_FOUND = 'lead_not_found',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_EVENT_TYPE = 'INVALID_EVENT_TYPE',
  EMPTY_EVENT = 'EMPTY_EVENT',
  VALUE_NOT_BASE64 = 'VALUE_NOT_BASE64',
  KAFKA_CLIENT_ERROR = 'KAFKA_CLIENT_ERROR',
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
}
