// Generated by https://quicktype.io

export interface IJobs {
  status: boolean;
  message: string;
  links: Links;
  meta: Meta;
  data: Datum[];
}
export interface IJob {
  status?: boolean | undefined;
  message?: string | undefined;
  data?: Datum | undefined;
  job?:GetJobResponseById;
}

interface Datum {
  id: number;
  recruiter_id: null;
  business_id: number;
  job_status_id: number;
  name: string;
  description: string;
  status: boolean;
  contract_type: string;
  summary: string;
  salary: number;
  min_salary: number;
  max_salary: number;
  hourly_wage: number;
  end_date: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  contract_time: string;
  is_visible: boolean;
  user_uuid: string;
  topic: string;
  business: Business;
  recruiter: null;
  owner: Owner;
  applications: any[];
  skills: Skill[];
  job?:GetJobResponseById;
}

interface Business {
  id: number;
  user_workplace_id: number;
  user_uuid: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  workplace: Workplace;
}
interface Workplace {
  id: number;
  user_uuid: string;
  start_date: string;
  end_date: string;
  description: string;
  work_here: boolean;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  position: string;
  workplace_id: number;
  workplace_name: string;
  enable_business: string;
}

export interface Owner {
  id: number;
  user_uuid: string;
  purpose: null;
  country_id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: null;
  subtitle: string;
  summary: string;
  profile_picture_url: string;
  profile_banner_url: string;
  is_talent: boolean;
  google_id: null;
  phone: string;
  contact_phone2: null;
  facebook_url: string;
  linkedin_url: string;
  github_url: null;
  contact_email: null;
  contact_phone: null;
  city_id: number;
  paypal_email: string;
  paypal_url: null;
  algo_address: null;
  twitter_url: string;
  person: Person;
  city?: City;
  country?: Country;
}

export interface City {
  id: number;
  country_iso2: string;
  name: string;
  lat: number;
  lng: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: null;
}

export interface Country {
  id: number;
  name: string;
  nombre: string;
  nom: string;
  iso2: string;
  iso3: string;
  phone_code: string;
  created_at: Date;
  updated_at: Date;
  deleted_at: null;
}

export interface Person {
  uuid: string;
  name: string;
  last_name: string;
  phone: string;
  document_type: string;
  document_number: string;
  email: string;
}

interface Skill {
  id: number;
  name: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}

export interface Links {
  first: string;
  last: string;
  prev: string;
  next: string;
}

export interface Meta {
  start: number;
  length: number;
  current_page: number;
  from: number;
  last_page: number;
  path: string;
  per_page: number;
  to: number;
  showing: number;
  total: number;
  fields_map: { [key: string]: string };
}
 interface GetJobResponseById {
  id: number
  business: Business
}

interface Business {
  user_workplace_id: number
  user_uuid: string
  owner: JobResponseOwner
}

interface JobResponseOwner {
  id: number
  user_uuid: string
  profile_picture_url: string
  users_industry: any
}