services:
  backend:
    container_name: ${CONTAINER_NAME}_backend
    image: ${IMAGE_DEV}
    working_dir: /app
    command: "npm run watch"
    networks: 
      - matrix-local
    volumes:
      - ./app:/app
      - $HOME/.aws:/home/node/.aws
    environment:
      - AWS_SDK_LOAD_CONFIG=1
    stdin_open: true

networks:
  matrix-local:
    name: matrix-local
