'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface) {
    return queryInterface.bulkInsert('skills', [
      {name:'.Net framework',required:true},
      {name:'Adobe',required:true},
      {name:'Angular 2+',required:true},
      {name:'Angular JS',required:true},
      {name:'Asp .Net',required:true},
      {name:'AWS',required:true},
      {name:'Blockchain',required:true},
      {name:'C#',required:true},
      {name:'C++',required:true},
      {name:'Cefi',required:true},
      {name:'Css',required:true},
      {name:'css3',required:true}, 
      {name:'DeFi',required:true},
      {name:'Django',required:true},
      {name:'Docker',required:true},
      {name:'Drupal',required:true},
      {name:'Express. JS',required:true},
      {name:'Figma',required:true},
      {name:'Flask',required:true},
      {name:'Flutter',required:true},
      {name:'GCP (Google cloud Platform)',required:true},
      {name:'Git',required:true},
      {name:'Go',required:true},
      {name:'Graphic Design',required:true},
      {name:'Hadoop',required:true},
      {name:'Heroku',required:true},
      {name:'html',required:true},
      {name:'Ionic',required:true},
      {name:'Java',required:true},
      {name:'Java mobile',required:true},
      {name:'Java script Back end',required:true},
      {name:'JavaScript',required:true},
      {name:'Jquery',required:true},
      {name:'Kotlin',required:true},
      {name:'Kubernetes',required:true},
      {name:'Laravel',required:true},
      {name:'Linux',required:true},
      {name:'Mattplotlib',required:true},
      {name:'Mongo DB',required:true},
      {name:'MSSQL',required:true},
      {name:'Node.js',required:true},
      {name:'Numpy',required:true},
      {name:'Objetive C',required:true},
      {name:'Oracle DB',required:true},
      {name:'Pandas',required:true},
      {name:'PHP',required:true},
      {name:'Postgre SQL',required:true},
      {name:'Product Design',required:true},
      {name:'Project management',required:true},
      {name:'Prototyping ',required:true},
      {name:'PySpark',required:true},
      {name:'Python',required:true},
      {name:'R',required:true},
      {name:'React JS',required:true},
      {name:'Reacti native',required:true},
      {name:'Redis',required:true},
      {name:'Refi',required:true},
      {name:'Rhel',required:true},
      {name:'Ruby',required:true},
      {name:'Scala',required:true},
      {name:'Scikit-learn',required:true},
      {name:'SciPy',required:true},
      {name:'Scrum',required:true},
      {name:'Selenium',required:true},
      {name:'Solana',required:true},
      {name:'Solidity',required:true},
      {name:'Spark',required:true},
      {name:'Spring boot',required:true},
      {name:'Spring framework',required:true},
      {name:'SQL',required:true},
      {name:'SQL Alchemy',required:true},
      {name:'SQL Lite',required:true},
      {name:'Swift',required:true},
      {name:'Tensorflow',required:true},
      {name:'Type script',required:true},
      {name:'Usability Testing',required:true},
      {name:'User Research',required:true},
      {name:'Vue JS',required:true},
      {name:'Wordpress',required:true},
      {name:'Figma',required:true},
      {name:'Marvel',required:true},
      {name:'Near',required:true},
      {name:'AI',required:true}
  ]);
  },

  async down (queryInterface) {
    return queryInterface.bulkDelete('skills', null, {});
  }
};
