#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef DIDM_CORE_SWIFT_H
#define DIDM_CORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="didm_core",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC9didm_core7Account")
@interface Account : NSObject
@property (nonatomic, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nonnull organizationName;
@property (nonatomic, readonly) BOOL activeOTPAuth;
@property (nonatomic, readonly) BOOL activePushAuth;
@property (nonatomic, readonly) BOOL activeQRAuth;
@property (nonatomic, readonly) BOOL activePushAlert;
@property (nonatomic) BOOL activeFaceAuth;
@property (nonatomic, readonly, copy) NSString * _Nonnull registrationDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull activationURL;
@property (nonatomic, readonly) NSInteger registrationMethod;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP9didm_core22AccountManagerProtocol_")
@protocol AccountManagerProtocol
- (void)saveAccountWithAccount:(Account * _Nonnull)account;
- (BOOL)removeAccountWithAccount:(Account * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Account *> * _Nonnull)getAccounts SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Account *> * _Nonnull)getAccountsPendingToMigrateRSAKey SWIFT_WARN_UNUSED_RESULT;
@end

@class InformationDevice;
@class NSData;

SWIFT_CLASS("_TtC9didm_core22AccountManagerImplCore")
@interface AccountManagerImplCore : NSObject <AccountManagerProtocol>
- (nonnull instancetype)initWithInformationDevice:(InformationDevice * _Nonnull)informationDevice OBJC_DESIGNATED_INITIALIZER;
- (void)saveAccountWithAccount:(Account * _Nonnull)account;
- (void)updateAccountInfoWithAccount:(Account * _Nonnull)account;
- (BOOL)removeAccountWithAccount:(Account * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Account *> * _Nonnull)getAccounts SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Account *> * _Nonnull)getAccountsPendingToMigrateRSAKey SWIFT_WARN_UNUSED_RESULT;
- (void)removeAllAccounts;
- (void)receivePushServiceId:(NSData * _Nonnull)data;
- (void)setApplicationName:(NSString * _Nonnull)name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC9didm_core14AppCompability")
@interface AppCompability : NSObject
@property (nonatomic, readonly) BOOL forceUpdate;
@end

@class TransactionInfo;
@class AGSDKError;

SWIFT_PROTOCOL("_TtP9didm_core24AuthenticationController_")
@protocol AuthenticationController
- (void)decryptScannedCode:(NSString * _Nullable)mks withAccount:(Account * _Nullable)account onSuccess:(void (^ _Nonnull)(TransactionInfo * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(AGSDKError * _Nonnull))onFailure;
@end


SWIFT_CLASS("_TtC9didm_core28AuthenticationControllerCore")
@interface AuthenticationControllerCore : NSObject <AuthenticationController>
- (void)decryptScannedCode:(NSString * _Nullable)mks withAccount:(Account * _Nullable)account onSuccess:(void (^ _Nonnull)(TransactionInfo * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(AGSDKError * _Nonnull))onFailure;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ProcessMode;

SWIFT_CLASS("_TtC9didm_core16BiometricProcess")
@interface BiometricProcess : NSObject
@property (nonatomic, readonly, strong) ProcessMode * _Nonnull enrollment;
@property (nonatomic, readonly, strong) ProcessMode * _Nonnull authentication;
@end

typedef SWIFT_ENUM(NSInteger, BiometricTransactionType, open) {
  BiometricTransactionTypeNONE_BIOMETRIC = 0,
  BiometricTransactionTypeFACE_AUTHENTICATION = 2,
  BiometricTransactionTypeFACE_AUTHENTICATION_LIVENESS = 3,
  BiometricTransactionTypeFACE_ENROLLMENT = 5,
};


SWIFT_PROTOCOL("_TtP9didm_core25BundleInformationProtocol_")
@protocol BundleInformationProtocol
- (NSString * _Nullable)getValueFromBundlePlistWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (BOOL)existAttributeBundlePlistWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9didm_core21BusinessMKSController")
@interface BusinessMKSController : NSObject
- (nonnull instancetype)initWithAccount:(Account * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
- (NSData * _Nullable)aesEncryptWithLastModeWithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (void)setSignatureWithSignature:(NSString * _Nonnull)signature;
- (NSDictionary<NSString *, id> * _Nullable)getMksWithMessage:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)decryptMessageJsonWithMks:(NSDictionary<NSString *, id> * _Nonnull)mks SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSignatureWithMessage:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValidSignatureWithMks:(NSDictionary<NSString *, id> * _Nonnull)mks SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol OnServerParametersErrors;
@protocol OnClientArgumentsErrors;

SWIFT_CLASS("_TtC9didm_core22ChallengeOTPController")
@interface ChallengeOTPController : NSObject
- (NSString * _Nullable)generateOtpTokenFromAlphaNumericChallengeQuestionWithQuestion:(NSString * _Nonnull)question date:(uint64_t)date tagAccount:(NSString * _Nonnull)tagAccount onServerParametersDelegate:(id <OnServerParametersErrors> _Nonnull)onServerParametersDelegate onClientArgumentsDelegate:(id <OnClientArgumentsErrors> _Nonnull)onClientArgumentsDelegate error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9didm_core22ChallengeOtpParameters")
@interface ChallengeOtpParameters : NSObject
- (nonnull instancetype)initWithSeedParameter:(NSString * _Nonnull)seedParameter questionParameter:(NSString * _Nonnull)questionParameter timeStampParameter:(uint64_t)timeStampParameter timeStampValueParameter:(NSInteger)timeStampValueParameter truncationOutputParameter:(NSInteger)truncationOutputParameter OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSeedParameter:(NSString * _Nonnull)seedParameter timestampTypeParameter:(NSString * _Nonnull)timestampTypeParameter timeStampValueParameter:(NSInteger)timeStampValueParameter truncationOutputParameter:(NSInteger)truncationOutputParameter OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9didm_core7Channel")
@interface Channel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull channelName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ChannelConfigResponse;

SWIFT_CLASS("_TtC9didm_core26ChannelConfigNetworkClient")
@interface ChannelConfigNetworkClient : NSObject
- (nonnull instancetype)initWithAccount:(Account * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
- (void)requestChannelConfigurationWithUrl:(NSString * _Nonnull)url onSuccess:(void (^ _Nonnull)(ChannelConfigResponse * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(AGSDKError * _Nonnull))onFailure;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ResponseCode;
@class FaceServerGestures;

SWIFT_CLASS("_TtC9didm_core21ChannelConfigResponse")
@interface ChannelConfigResponse : NSObject
@property (nonatomic, readonly, strong) ResponseCode * _Nullable response;
@property (nonatomic, readonly, strong) AppCompability * _Nullable app;
@property (nonatomic, readonly, strong) FaceServerGestures * _Nullable factors;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (NSData * _Nullable)getData SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TransactionStatus : NSInteger;
@class NSNumber;

SWIFT_PROTOCOL("_TtP9didm_core23DIDAuthenticationParser_")
@protocol DIDAuthenticationParser
- (TransactionInfo * _Nullable)parseTransactionInfoWithBusinessMessage:(NSDictionary<NSString *, id> * _Nonnull)businessMessage account:(Account * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
- (TransactionInfo * _Nullable)parseTransactionInfoWithBusinessMessage:(NSDictionary<NSString *, id> * _Nonnull)businessMessage account:(Account * _Nonnull)account status:(enum TransactionStatus)status registrationDate:(NSNumber * _Nullable)registrationDate SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9didm_core27DIDAuthenticationParserImpl")
@interface DIDAuthenticationParserImpl : NSObject <DIDAuthenticationParser>
- (TransactionInfo * _Nullable)parseTransactionInfoWithBusinessMessage:(NSDictionary<NSString *, id> * _Nonnull)businessMessage account:(Account * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
- (TransactionInfo * _Nullable)parseTransactionInfoWithBusinessMessage:(NSDictionary<NSString *, id> * _Nonnull)businessMessage account:(Account * _Nonnull)account status:(enum TransactionStatus)status registrationDate:(NSNumber * _Nullable)registrationDate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DidSdkSyncronizeModel;

SWIFT_CLASS("_TtC9didm_core34DidSdkAuthCoreSyncronizeController")
@interface DidSdkAuthCoreSyncronizeController : NSObject
- (nonnull instancetype)initWithModel:(DidSdkSyncronizeModel * _Nonnull)model OBJC_DESIGNATED_INITIALIZER;
- (BOOL)executeDidSdkSyncronizationAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9didm_core24DidSdkPersistenceManager")
@interface DidSdkPersistenceManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setAdditionalInformationForPush:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (void)setAdditionalInformationForQr:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (void)setAdditionalInformationForFace:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
@end


SWIFT_CLASS("_TtC9didm_core21DidSdkSyncronizeModel")
@interface DidSdkSyncronizeModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull tagNewInstall;
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersionTag;
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceAttrDeviceId;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountAttrDeviceId;
- (nonnull instancetype)initWithTagNewInstall:(NSString * _Nonnull)tagNewInstall sdkVersionTag:(NSString * _Nonnull)sdkVersionTag sdkVersion:(NSString * _Nonnull)sdkVersion serviceAttrDeviceId:(NSString * _Nonnull)serviceAttrDeviceId accountAttrDeviceId:(NSString * _Nonnull)accountAttrDeviceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9didm_core18FaceServerGestures")
@interface FaceServerGestures : NSObject
@property (nonatomic, readonly, strong) BiometricProcess * _Nonnull face;
@end


SWIFT_CLASS("_TtC9didm_core8Gestures")
@interface Gestures : NSObject
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull faceGestures;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9didm_core22GlobalConfigController")
@interface GlobalConfigController : NSObject
- (void)updateGlobalConfigWithUrlString:(NSString * _Nonnull)urlString body:(NSData * _Nonnull)body account:(Account * _Nonnull)account seed:(NSString * _Nonnull)seed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9didm_core17InformationDevice")
@interface InformationDevice : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getModelDevice SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSystemVersionDevice SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getApplicationName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getPhoneId SWIFT_WARN_UNUSED_RESULT;
- (void)registerPhoneId:(NSString * _Nonnull)phoneId;
- (NSString * _Nonnull)getMobileId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAppInstallId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAppInstallIdSha256 SWIFT_WARN_UNUSED_RESULT;
- (void)resetAppInstallId;
@end

@class KeyChainBuilder;

SWIFT_PROTOCOL("_TtP9didm_core20KeyChainDataProtocol_")
@protocol KeyChainDataProtocol
- (KeyChainBuilder * _Nonnull)createQuery SWIFT_WARN_UNUSED_RESULT;
- (BOOL)saveKeyChainWithValue:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (BOOL)updateKeyChainWithValueToUpdate:(NSString * _Nonnull)valueToUpdate SWIFT_WARN_UNUSED_RESULT;
- (BOOL)updateKeyChainWithQueryToUpdate:(NSDictionary<NSString *, id> * _Nonnull)queryToUpdate attributesToUpdate:(NSDictionary<NSString *, id> * _Nonnull)attributesToUpdate SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getValueKeyChain SWIFT_WARN_UNUSED_RESULT;
- (BOOL)existKeyChain SWIFT_WARN_UNUSED_RESULT;
- (void)removeKeyChain;
@end


SWIFT_PROTOCOL("_TtP9didm_core27KeyChainEncodingKeyProtocol_")
@protocol KeyChainEncodingKeyProtocol
- (void)saveEncodingKeyWithKey:(NSString * _Nonnull)key;
- (NSString * _Nonnull)getEncodingKeyV7FromKeyChain SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9didm_core19KeyChainEncodingKey")
@interface KeyChainEncodingKey : NSObject <KeyChainEncodingKeyProtocol>
- (nonnull instancetype)initWithBundleInformation:(id <BundleInformationProtocol> _Nonnull)bundleInformation keyChainData:(id <KeyChainDataProtocol> _Nonnull)keyChainData OBJC_DESIGNATED_INITIALIZER;
- (void)saveEncodingKeyWithKey:(NSString * _Nonnull)key;
- (NSString * _Nonnull)getEncodingKeyV7FromKeyChain SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface NSString (SWIFT_EXTENSION(didm_core))
- (NSString * _Nonnull)getActivationDate SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9didm_core10OTPEncrypt")
@interface OTPEncrypt : NSObject
- (NSString * _Nonnull)encryptWithTokenDic:(NSDictionary * _Nonnull)tokenDic SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nonnull)decryptWithToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP9didm_core20OTPKeyLegacyProtocol_")
@protocol OTPKeyLegacyProtocol
- (NSDictionary * _Nonnull)getTokenInformationWithData:(NSString * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9didm_core12OTPKeyLegacy")
@interface OTPKeyLegacy : NSObject <OTPKeyLegacyProtocol>
- (nonnull instancetype)initWithKeyChainEncodingKey:(id <KeyChainEncodingKeyProtocol> _Nonnull)keyChainEncodingKey OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary * _Nonnull)getTokenInformationWithData:(NSString * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (void)saveOTPKeyWithKey:(NSString * _Nonnull)key;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9didm_core19OTPKeyLegacyBuilder")
@interface OTPKeyLegacyBuilder : NSObject
- (OTPKeyLegacy * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP9didm_core23OnClientArgumentsErrors_")
@protocol OnClientArgumentsErrors
- (void)onInvalidChallengeLengthWithLength:(NSInteger)length reason:(NSString * _Nonnull)reason;
- (void)onMissingPasswordWithReason:(NSString * _Nonnull)reason;
@end


SWIFT_PROTOCOL("_TtP9didm_core24OnServerParametersErrors_")
@protocol OnServerParametersErrors
- (void)onInvalidTimeStampLengthWithLength:(NSInteger)length reason:(NSString * _Nonnull)reason;
- (void)onInvalidLengthTokenWithLength:(NSInteger)length reason:(NSString * _Nonnull)reason;
@end


SWIFT_CLASS("_TtC9didm_core11ProcessMode")
@interface ProcessMode : NSObject
@property (nonatomic, readonly) NSInteger challengeDuration;
@end


SWIFT_CLASS("_TtC9didm_core23PushInboxControllerCore")
@interface PushInboxControllerCore : NSObject
- (nonnull instancetype)initWithAccount:(Account * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getInitialDate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP9didm_core22RegistrationController_")
@protocol RegistrationController
- (void)registerDeviceWithUrl:(NSString * _Nonnull)url registrationMethod:(NSInteger)registrationMethod registrationResult:(void (^ _Nonnull)(NSString * _Nonnull))registrationResult;
- (void)registerDeviceWithUrl:(NSString * _Nonnull)url registrationMethod:(NSInteger)registrationMethod additionalData:(NSString * _Nullable)additionalData onSuccess:(void (^ _Nonnull)(void))onSuccess onFailure:(void (^ _Nonnull)(AGSDKError * _Nonnull))onFailure;
@end


SWIFT_CLASS("_TtC9didm_core26RegistrationControllerImpl")
@interface RegistrationControllerImpl : NSObject <RegistrationController>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)registerDeviceWithUrl:(NSString * _Nonnull)url registrationMethod:(NSInteger)registrationMethod registrationResult:(void (^ _Nonnull)(NSString * _Nonnull))registrationResult;
- (void)registerDeviceWithUrl:(NSString * _Nonnull)url registrationMethod:(NSInteger)registrationMethod additionalData:(NSString * _Nullable)additionalData onSuccess:(void (^ _Nonnull)(void))onSuccess onFailure:(void (^ _Nonnull)(AGSDKError * _Nonnull))onFailure;
@end


SWIFT_CLASS("_TtC9didm_core12ResponseCode")
@interface ResponseCode : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull responseCodeType;
@property (nonatomic, readonly, copy) NSString * _Nonnull responseCodeTypeDescription;
@end


SWIFT_CLASS("_TtC9didm_core19ResponseManagerCore")
@interface ResponseManagerCore : NSObject
+ (NSString * _Nullable)getAuthenticationBodyWithTransactionInfo:(NSDictionary<NSString *, id> * _Nonnull)transactionInfo account:(Account * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getAuthenticationForFaceWithTransactionId:(NSString * _Nonnull)transactionId SWIFT_WARN_UNUSED_RESULT;
+ (AGSDKError * _Nonnull)getAGSDKErrorWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
+ (AGSDKError * _Nonnull)getBiometricErrorWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum TransactionType : NSInteger;

SWIFT_CLASS("_TtC9didm_core15TransactionInfo")
@interface TransactionInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull transactionID;
@property (nonatomic, readonly, copy) NSString * _Nonnull subject;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull subjectNotification;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageNotification;
@property (nonatomic, readonly, copy) NSString * _Nonnull urlToResponse;
@property (nonatomic, readonly, copy) NSString * _Nonnull urlToConfigFaceID;
@property (nonatomic, readonly) enum TransactionType type;
@property (nonatomic, readonly) enum BiometricTransactionType biometricType;
@property (nonatomic, readonly) uint64_t timeStamp;
@property (nonatomic, readonly) enum TransactionStatus status;
@property (nonatomic, readonly, strong) Account * _Nullable account;
@property (nonatomic, readonly, copy) NSString * _Nonnull transactionOfflineCode;
@property (nonatomic, readonly, strong) Gestures * _Null_unspecified gestures;
@property (nonatomic, readonly, strong) Channel * _Null_unspecified channel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TransactionStatus, open) {
  TransactionStatusALL = 0,
  TransactionStatusAPPROVED = 1010,
  TransactionStatusPENDING = 1011,
  TransactionStatusNOT_APPROVED = 1012,
  TransactionStatusEXPIRED = 1013,
  TransactionStatusMAX_WRONG_ATTEMPTS = 1014,
};

typedef SWIFT_ENUM(NSInteger, TransactionType, open) {
  TransactionTypeNONE = 0,
  TransactionTypePUSH_AUTHENTICATION = 1,
  TransactionTypePUSH_ALERT = 2,
  TransactionTypeBIOMETRIC_AUTHENTICATION = 3,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
