  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.enviroment = undefined;
  var dev = {
    client_id: '',
    client_secret: '',
    detectIDUrl: '',
    ssoUrl: '',
    initURL: '',
    baseURL: '',
    maximumApprove: 0,
    whiteMarchProduction: 0,
    numeroIntentosLogin: 0,
    versionAppEmpresasIOS: '',
    versionAppEmpresasAndroid: '',
    templateEmailInicioSesion: '',
    emailBanbif: '',
    domainUrl: '',
    domainName: 'appsopsprvdes.dombif.peru',
    shaDomain: '',
    key: '',
    iv: '',
    countFalling: 0,
    contextUrl: 'Banbif-API',
    clientInformationInitial: 'https://banbif-empresas-mobile-conf.appsopsprvdes.dombif.peru',
    siteKeyCaptcha: '',
    pinninOk: true,
    disableDebugEmulators: false
  };
  var uat = {
    client_id: '',
    client_secret: '',
    detectIDUrl: '',
    ssoUrl: '',
    initURL: '',
    baseURL: '',
    maximumApprove: 0,
    whiteMarchProduction: 0,
    numeroIntentosLogin: 0,
    versionAppEmpresasIOS: '',
    versionAppEmpresasAndroid: '',
    templateEmailInicioSesion: '',
    emailBanbif: '',
    domainUrl: '',
    domainName: 'uatapps.banbifapimarket.com.pe',
    shaDomain: '',
    key: '',
    iv: '',
    countFalling: 0,
    contextUrl: 'Banbif-API-External',
    clientInformationInitial: 'https://banbif-empresas-mobile-conf.uatapps.banbifapimarket.com.pe',
    siteKeyCaptcha: '',
    pinninOk: false,
    disableDebugEmulators: false
  };
  var prd = {
    client_id: '',
    client_secret: '',
    detectIDUrl: '',
    ssoUrl: '',
    initURL: '',
    baseURL: '',
    maximumApprove: 0,
    whiteMarchProduction: 0,
    numeroIntentosLogin: 0,
    versionAppEmpresasIOS: '',
    versionAppEmpresasAndroid: '',
    templateEmailInicioSesion: '',
    emailBanbif: '',
    domainUrl: '',
    domainName: 'apps.banbifapimarket.com.pe',
    shaDomain: '',
    key: '',
    iv: '',
    countFalling: 0,
    contextUrl: 'Banbif-API-External',
    clientInformationInitial: 'https://banbif-empresas-mobile-conf.apps.banbifapimarket.com.pe',
    siteKeyCaptcha: '',
    pinninOk: true,
    disableDebugEmulators: false
  };
  var enviroment = exports.enviroment = uat;
