workflows:
  flutter-android:
    name: Flutter Android
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    environment:
      android_signing:
        - Jardines-de-la-paz
      groups:
        - firebase_credentials
      flutter: stable
    scripts:
      - name: Set up key.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/key.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build APK with Flutter
        script: | 
          UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          flutter build apk --release \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.1.$UPDATED_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:601405345282:android:a2e65516fd6e6cada5e11b
          artifact_type: 'apk'
          groups:
            - users