eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: auth
    password: secreto
  jpa.show-sql: true
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
