const dev = {
	client_id: '',
	client_secret: '',
	detectIDUrl: '',
	ssoUrl: '',
	initURL: '',
	baseURL: '',
	maximumApprove: 0,
	whiteMarchProduction: 0,
	numeroIntentosLogin: 0,
	versionAppEmpresasIOS: '',
	versionAppEmpresasAndroid: '',
	templateEmailInicioSesion: '',
	emailBanbif: '',
	domainUrl: '',
	domainName: '*.appsopsprvdes.dombif.peru',
	shaDomain: '',
	key: '',
	iv: '',
	countFalling: 0,
	contextUrl: 'Banbif-API',
	clientInformationInitial: 'https://banbif-empresas-mobile-conf.appsopsprvdes.dombif.peru',
	siteKeyCaptcha: '',
	pinninOk: true
}

const uat = {
	client_id: '',
	client_secret: '',
	detectIDUrl: '',
	ssoUrl: '',
	initURL: '',
	baseURL: '',
	maximumApprove: 0,
	whiteMarchProduction: 0,
	numeroIntentosLogin: 0,
	versionAppEmpresasIOS: '',
	versionAppEmpresasAndroid: '',
	templateEmailInicioSesion: '',
	emailBanbif: '',
	domainUrl: '',
	domainName: '*.uatapps.banbifapimarket.com.pe',
	shaDomain: '',
	key: '',
	iv: '',
	countFalling: 0,
	contextUrl: 'Banbif-API-External',
	clientInformationInitial: 'https://banbif-empresas-mobile-conf.uatapps.banbifapimarket.com.pe',
	siteKeyCaptcha: '',
	pinninOk: true
}

const prd = {
	client_id: '',
	client_secret: '',
	detectIDUrl: '',
	ssoUrl: '',
	initURL: '',
	baseURL: '',
	maximumApprove: 0,
	whiteMarchProduction: 0,
	numeroIntentosLogin: 0,
	versionAppEmpresasIOS: '',
	versionAppEmpresasAndroid: '',
	templateEmailInicioSesion: '',
	emailBanbif: '',
	domainUrl: '',
	domainName: '*.apps.banbifapimarket.com.pe',
	shaDomain: '',
	key: '',
	iv: '',
	countFalling: 0,
	contextUrl: 'Banbif-API-External',
	clientInformationInitial: 'https://banbif-empresas-mobile-conf.apps.banbifapimarket.com.pe',
	siteKeyCaptcha: '',
	pinninOk: true
}

export let enviroment = uat;
